global:
  scrape_interval:     10s
  evaluation_interval: 10s
 
scrape_configs:
  - job_name: user_profile
    static_configs:
      - targets: ['127.0.0.1:27112']
        labels:
          instance: user_profile
 
  - job_name: pool_data
    static_configs:
      - targets: ['127.0.0.1:27113']
        labels:
          instance: pool_data